### ISSUE TITLE
Best practices for feature detection of DOM API

### ISSUE THREAD

**Issue by alice** [w3ctag/design-principles#137]
One example: WebXR have a feature detection method, `supportsSession()`, which returns a promise which rejects if the session type is not supported.

Should this return a `Promise<boolean>`, on the principle that feature detection shouldn't throw?

Also, what other best practices are there for feature detection?

cc @torgo

**Comment by torgo** [comment]
We have some text in [section 2.3](https://w3ctag.github.io/design-principles/#feature-detect) (New Features should be Detectable) so if we have more to say on this topic it should probably be added here.

**Comment by kenchris** [comment]
I think there is some overlap between feature detection and fingerprinting (and private browsing mode).

Of the top of my head I have heard different recommendations at different times.

Examples:
- don't expose the objects etc when feature is not available (like no underlying hardware gyroscope for instance)
- always expose (due to avoiding fingerprinting) but let object throw (NotAvailableError or similar) when instantiated - this way you can see whether the browser support the feature or not, but not whether the hardware does

All of this leads to different design and confuses users and spec authors. I am not sure what would be the right answer but it deserves some thought and it also requires some research on what kind of different solutions are in use today.

@anssik @slightlyoff @reillyeon @beaufortfrancois

**Comment by torgo** [comment]
Suggest having a dedicated breakout session on this during the non-design-review week next month.

**Comment by kenchris** [comment]
Current different ways:

- Presence of a namespace
- Presence of an object
  like `if ('NFCReader') in window
- properties on objects, eg. Media Capture

**Comment by torgo** [comment]
@triblondon do you have opinions here?

**Comment by tomayac** [comment]
Not strictly feature detection, but maybe still interesting: the Shape Detection API has a [`BarcodeDetector.getSupportedFormats()`](https://wicg.github.io/shape-detection-api/#dom-barcodedetector-getsupportedformats) method, since presence of the `BarcodeDetector` alone may not be enough if the objective is scanning “weird” barcode formats that not all platforms may support.

**Comment by scunliffe** [comment]
I wonder if there is a solution that enables developers to detect features, but also restricts/reduces fingerprinting?

e.g. browsers are smart enough now to differentiate between a user-driven-event like a mouse click vs. a simulated .click() event applied to a link/button to determine if triggered code like a window.open() call should be allowed or not. This was done to stop spammy websites from launching popup ads, but still allow "desired" popups in web applications.

As such, for many of these features... I wonder if a Just In Time (JIT) model might work where by a check to detect a feature would **_only_** be allowed if the code following it attempts to use it.

```
if('NFCReader' in window){ // check is allowed
  doNFCStuff();
}

if('NFCReader' in window){ // check is denied/blocked
  addToFingerprintingData();
}
```

Not foolproof by any means, but mixed with browser permissions by domain etc. might cover most cases.

**Comment by dbaron** [comment]
> always expose (due to avoiding fingerprinting) but let object throw (NotAvailableError or similar) when instantiated - this way you can see whether the browser support the feature or not, but not whether the hardware does

It seems like this doesn't help much with fingerprinting, since it's still exposing the information about whether the device is available or not.

It's also worth noting that "implementation doesn't support X" and "implementation supports X but there aren't any devices available" are different results that pages might want to handle in different ways.

**Comment by dbaron** [comment]
... so what I'm saying is that detection of the support for a feature in the implementation should generally be separate from detection of whether a device to do something with that feature is available.  (And the latter might be after a request for user permission.)

**Comment by torgo** [comment]
Discussed and agreed to close at our [f2f](https://github.com/w3ctag/meetings/tree/gh-pages/2020/09-europe).
