### ISSUE TITLE
Link to the CSSWG's FAQ

### ISSUE THREAD

**Issue by frivoal** [w3ctag/design-principles#186]
I think a link to the https://wiki.csswg.org/faq may be appropriate from the CSS Section of design principles would be appropriate. This isn't exactly the same topic: as the TAG's document describes how to do things, while the FAQ describes why certain things cannot be done, but it feels that FAQ could be of interest to readers of the TAG's document.

**Comment by dbaron** [comment]
@plinss and I looked at this during a breakout in the TAG's virtual face-to-face today.

We're not sure how useful this link would be; we're trying to link to things that people designing new features would find generally useful.  We think this FAQ probably doesn't fall into that category, at least partly because it's targeted more at the audience of developers using CSS rather than those designing new CSS features.

(We're also a little unsure how *frequently* some of these frequently asked questions are; perhaps it's the obscurity of the first one that threw us, though.)

We'd be happy to link to a set of CSS principles that fills the role of advice for designers of new features.

**Comment by frivoal** [comment]
> We're also a little unsure how frequently some of these frequently asked questions are; perhaps it's the obscurity of the first one that threw us

I start the FAQ because I was tired of answering the same questions. For sure, with a sample of one, there's no statistical relevance to it, and just because I've faced them often enough to want to start an FAQ doesn't mean that they're often asked in the absolute.

> it's targeted more at the audience of developers using CSS rather than those designing new CSS features

I think it's somewhere in between. It's not really targeted at people who're far down the path of designing css features, but it is targeted at people who're proposing to change css in some way or to add something. People who're considering beginning incubation, in a way.

Not so much "make sure you design your CSS feature right", but rather "make sure you don't waste time attempting to design something that is known to be impossible / inacceptable".
