### ISSUE TITLE
Grammars vs. parsers

### ISSUE THREAD

**Issue by domenic** [w3ctag/design-principles#19]
Grammars are good for author conformance and anything that doesn't need error recovery. Parsers end up being more necessary in the real world: HTML, URL, CSS examples in the web's history.

Discussion in Berlin day 3 minutes.

**Comment by domenic** [comment]
@mnot might be able to give some of the history here from the HTTP/protocol-level side.

**Comment by mnot** [comment]
Grammars (e.g., ABNF) are easier to understand for the reader, and are also a lot easier to define extensions for without monkey-patching (e.g., any extension to the current Cookie spec requires extensive monkey-patching). But yes, ABNF doesn't define error recovery well.

I don't know that that's an intrinsic property of grammars, however; it's just that there isn't a well-defined processing model for things defined by ABNF, so the corner cases are all undefined. 

We're looking at alternative approaches in HTTP, e.g.:
  https://tools.ietf.org/html/draft-reschke-http-jfv-01
which defines a regular syntax that HTTP header fields can opt into, and if they do, it has well-defined error handling (although it probably needs to be better defined :)

The holy grail is a syntax that's easy to specify, easy to understand as a reader, easy to author, easy to extend, and well-defined enough for implementations to get good interop, even in the error handling cases. 

Neither the ABNF grammar approach nor the imperatively-defined parser approach meets all of those goals.

**Comment by annevk** [comment]
Extensions meaning "cannot revive the base specification" is just a process bug. Non-maintained specifications, just like code, are problematic.

**Comment by mnot** [comment]
Generally agreed, especially for many (not all) Web-related tech. 

However, when you have a spec that's being used by multiple communities for different use cases, it's not realistic to pile all of their extensions into the core spec.

**Comment by annevk** [comment]
But then you don't generally want extensions at the parser level, since then parsers can no longer be used across these communities. You need something on top.

**Comment by mnot** [comment]
Ideally, you parse and then hand *something* off to the extension (a string, a data structure, whatever). I think the trick is providing an appropriate balance of context and isolation to that extension so that it can be defined in a truly independent way.

**Comment by sideshowbarker** [comment]
> Grammars (e.g., ABNF) are easier to understand for the reader,

While that may be true for some class of readers (though I think not really even for normal authors), I think it’s not true for UA implementors. At least not for the purpose of providing what an UA implementor needs in order to implement that spec.

> The holy grail is a syntax that's easy to specify, easy to understand as a reader, easy to author, easy to extend, and well-defined enough for implementations to get good interop, even in the error handling cases.
> Neither the ABNF grammar approach nor the imperatively-defined parser approach meets all of those goals.

Yeah, I think you can never have all of those things, so you have to choose who you want to optimize the spec for. And for specs that define requirements for UAs, it seems right to optimize the spec for UA implementors (as opposed to authors or whoever else).

And in that case, especially if the spec defines UA requirements for how to consume/process Web content, then the parser-algorithm approach meets the well. Certainly I can’t think of any cases at all where I’ve ever seen a UA implementor say they didn’t like implementing from a parser algorithm and would rather have ABNF or some other kind of grammar or other formalism.

That said, if is spec is instead intended to define rules are for producing Web content (to be consumed as expected by UAs) then ABNF isn’t the worst way to do that, and other grammars or formalisms can work OK. But even then, I don’t think normal Web authors/developers find ABNF to be very easy to understand, nor most other existing grammar formalisms. I think what they actually find easiest to understand is natural-language prose that states the production requirements.

Also, normal authors normally don’t care to have error-recovery specified. They don’t need it. If anything, I think the definitions of error-recovery behavior in most cases just further confuse most of them.

Anyway, the fact that we keep having discussions about this grammar-vs-parser issue over the years to me suggests that the underlying problem is that we should not be creating specs that try to address the needs of normal authors along with the needs of implementors. Because after all these years I think think of a single example of spec where that’s ever been done well. Most all specs for the platform address the needs of authors very poorly. But quite a few now address the needs of UA implementors much better than any did, say, 10 years ago. And those are generally the same ones that have adopted the parser-algorithm approach to specifying the UA requirements.

**Comment by annevk** [comment]
@mnot once you have multiple extensions, order matters. So if multiple extensions are used by the same community, you need something more elaborate and ideally you just update the base, since that is what those communities will likely do, in order to gain perf et al.

**Comment by torgo** [comment]
We agree there are cases for each. Agreed in [Feb 2017 f2f](https://github.com/w3ctag/meetings/tree/gh-pages/2017/02-boston) we don't have consensus on advice to add to this document.

**Comment by annevk** [comment]
That is somewhat surprising. We have somewhat significant evidence that parsers work, whereas grammar-based solutions typically have holes.

**Comment by mnot** [comment]
I think a large part of the pushback on parsers is that it often requires you to get (and keep) a tremendous amount of state in your head before you can figure out what's going on.

Personally, for most Web-related things, I'm starting to prefer defining a parser and then a non-normative grammar with supporting text, so people can understand what's going on. 

Yes, it needs big warning flags.
