### ISSUE TITLE
Web APIs are not in fact just for JavaScript

### ISSUE THREAD

**Issue by bzbarsky** [w3ctag/design-principles#22]
In particular, they need to work from webasm as well.  It may be worth clarifying what section 1.1 of this document is _actually_ saying.

**Comment by domenic** [comment]
It's not clear that webasm has any meaningful processing model that we could say something about here. E.g., how does webasm represent a promise.

What would you say that this section is actually saying?

**Comment by bzbarsky** [comment]
I think the goal of this section is that APIs should "feel right" to JavaScript developers.

That's not necessarily the same as saying that APIs should only be developed with JavaScript in mind (e.g. various browser vendors have vetoed particular API designs because they couldn't implement them in their non-JavaScript-based implementation)...

**Comment by domenic** [comment]
I'm trying to say something stronger: that depending on JS concepts is kosher. I also don't really agree with the latter: these APIs return JS objects, maybe with internal slots. Someone could come up with a potentially-automated conversion, but even that will fail for prose-specified "object" return values and similar.

**Comment by domenic** [comment]
Let me put it this way. WebAssembly is a pretty speculative technology right now. People may be working on making it part of the web, and may be working on techniques for making web APIs accessible to it, but those are all speculative and nowhere near specced, shipping, or established. Once WebAssembly crosses that barrier, I expect there will be a better-defined processing model for how to expose web APIs to it. And along with that, there may be best practices to follow when designing your JS-exposed APIs such that they can be automatically converted to wasm-exposed APIs---things like "don't use the `object` return type," perhaps. But we don't really know what those are. I for one would anticipate them to include much more restrictive guidance (like "don't use any non-numeric return types"). It's impossible to say.

I think that when wasm becomes actually-specced, and the processing model for exposing JS APIs to wasm becomes actually-specced, then we can consider writing guidelines for writing wasm-exposed APIs in addition to JS-exposed ones. But the web only has JS-exposed ones right now, so that's what this document deals with.

**Comment by bzbarsky** [comment]
All I'm saying is that it's worth considering whether the objects involved may end up having non-JS consumers, and whether there are ways of defining APIs that can be done in way that is not thoroughly tied to JS but maps naturally into JS.

For example, having IDL dictionaries instead of just `object` and lots of prose.

**Comment by torgo** [comment]
I think it's OK to limit the scope of this document to Javascript APIs. Propose closing this issue.

**Comment by annevk** [comment]
Given that wasm is close to shipping that seems wrong?

**Comment by torgo** [comment]
From the call we're just having. We're not sure what a design principle for a WASM API would look like. What would be different about a WASM API?

**Comment by torgo** [comment]
@slightlyoff to write some more thoughts.

**Comment by slightlyoff** [comment]
@bzbarsky: can you be more explicit about the change in language you were were you looking for?

From what I've been able to glean from the WASM team here at Google, it seems that the current state of DOM access is a thunk through JS. While this is the case, and until we have a defined memory model for JS-based DOM APIs, WASM API design will continue to be downstream of JS API design. Happy to revisit once that memory model (and lifetime management) question is resolved. Until then, ¯\_(ツ)_/¯

**Comment by bzbarsky** [comment]
> @bzbarsky: can you be more explicit about the change in language you were were you looking for?

If I were sure, I would have proposed it.

But in terms of the _effects_ of the language on spec design, https://github.com/w3ctag/design-principles/issues/22#issuecomment-125835389 describes the problem I'm trying to solve.

**Comment by travisleithead** [comment]
Super. We have an interest in making the platform for coherent. We are pretty focused on JavaScript (reducing differences between DOM and JS). Today WebIDL gives us a mapping into JavaScript, and I think we would agree that we would like it to continue in this vein. Just speculating: for WebASM, I would think that there may be a way to define how WebASM bridges into WebIDL interface could be defined that meet that environment. So, we want WebIDL to be our lingua-franca. 

I think we should just take the WebASM evolution as it comes, and not worry too much about the gearing this document's text to it at this point.

**Comment by slightlyoff** [comment]
To add to what @travisleithead wrote, I think there's real value in encouraging folks to use IDL when that makes sense in their specs. That said, things like `dictionary` are...odd...from the JS perspective. A good future (from my perspective) is for dictionary to be more like a self-hosted JS object. Looking at the current mapping, I'm curious to know how different we are at a semantic level between `Object.create(null, ...)` and a Dictionary. What can we do to reduce the size of that difference?

**Comment by domenic** [comment]
What is odd about dictionaries? They are just a conceptual representation of normal JS objects, where all the property lookups happen once. They represent cases `foo({ option1: bar, option2: baz })`.

Nobody does `foo({ __proto__: null, option1: bar, option2: baz })`, so I don't think `Object.create(null)` is too relevant here.

If you were writing Web IDL bindings in JavaScript instead of in C++, a dictionary-accepting method would look like:

```js
function foo({ option1, option2 }) {
  // use option1, option2
}
```

which seems great to me.

**Comment by bzbarsky** [comment]
I think Alex's question is why we need a Dictionary type at all, as opposed to just using a null-prototype JS object to represent a Dictionary on the IDL side.

The answer is... nothing stops you from doing that, in some sense.  A Dictionary is just like an ES Record, really (once you've gotten past the create a dictionary from an object step).  It's a specification device.  In a self-hosting environment, you may well want to implement a Dictionary as a null-proto object.  SpiderMonkey does just that with Record in http://searchfox.org/mozilla-central/rev/afcf40f3eafd895611a839017730debb58a342a6/js/src/builtin/Utilities.js#67-70 for example.  In a non-self-hosted environment you'd use some other representation for either a Record or a Dictionary.

So why do we have a specification type at all?  It makes it a little simpler to reason about the behavior and prevents accidental coupling to behaviors that might get introduced for objects.  It simplifies having the thing exist in non-self-hosted environments.

Anyway, it sounds like we all agree that there is value in having some sort of "language agnostic" representation here.  This agreement just doesn't come through in the design principles.   ;)

P.S. I should note that any serious self-hosting setup will absolutely forbid you to do `Object.create` because you have no idea what that's actually going to do.  `{__proto__: null, stuff }` is safe, as is calling some built-in to create you a null-proto object...  Yes, this is a nitpick, but this whole discussion is about nits to some extent.
