### ISSUE TITLE
New principle for CSS? CSS syntax should not be able to create cycles

### ISSUE THREAD

**Issue by LeaVerou** [w3ctag/design-principles#265]
This comes up very frequently in the CSS WG when reviewing external proposals, so I was wondering if it should be added as a design principle?

A few examples where this came up:
https://github.com/w3c/csswg-drafts/issues/5827
https://github.com/w3c/csswg-drafts/issues/5729
https://github.com/w3c/csswg-drafts/issues/5461
https://github.com/w3c/csswg-drafts/issues/5228

We could also list strategies for avoiding cycles, such as:
- If the cycle is only present when a certain value type is used on certain properties, it can be special-cased to resolve to an inherited value in those properties (e.g. `em` units, `lh` units, `currentColor` keyword)
- General cycle detection via a dependency graph is too expensive for many user agents to implement, but in certain, limited cases it can be feasible. Custom properties are one of those cases.

Thoughts, @hober @atanassov @dbaron @plinss?

**Comment by plinss** [comment]
I'm opposed to this as a general design principle. I accept that there are many examples of CSS that rejected the possibility of cycles, but in general that was done due to implementation complexity or perceived performance impacts. As the platform matures, and more processing power becomes available, I expect cycle detection and resolution to become more practical and don't want to preclude it where appropriate. I've made this argument before in CSSWG meetings. Once upon a time (circa 1996-7) CSS1 selector matching was thought to be impossible due to performance concerns that turned out to be solvable.

There are many page layout techniques that the web doesn't (yet) do well (or at all), mostly due to cycles and race conditions that don't fit well with the current layout algorithms. That doesn't mean we shouldn't be trying to do them. E.g. footnotes in multicol or paged media, container queries, etc.

**Comment by LeaVerou** [comment]
I actually agree with @plinss so I'm going to go ahead and close this. 🙂
