### ISSUE TITLE
Avoid nondeterministic behavior

### ISSUE THREAD

**Issue by domenic** [w3ctag/design-principles#3]
Be very, very, very careful.

(A potential mitigation strategy would be purposefully injecting randomness, but nobody is very excited about this idea...)

**Comment by travisleithead** [comment]
Enumeration or properties in javascript?

**Comment by travisleithead** [comment]
Avoiding leaving to chance things that could return a list of things (e.g., camera, microphone devices).

**Comment by torgo** [comment]
Discussed at Tokyo f2f. @travisleithead to write something.

**Comment by torgo** [comment]
This has been open for a long time and we haven't been able to prioritize it. This may be because it's not a burning issue. It doesn't seem to have come up in any design reviews that we've been working on. It may be time to close this issue and get it off of our backlog so we can focus on more pressing principles work.
