### ISSUE TITLE
New principle: Avoid introducing new parser-blocking features

### ISSUE THREAD

**Issue by LeaVerou** [w3ctag/design-principles#329]
This was brought up here: https://github.com/whatwg/html/issues/2791#issuecomment-892790934
and I thought it's exactly the kind of thing we should have a principle about.

**Comment by torgo** [comment]
Hi @jakearchibald We were talking about writing something for our design principles doc that expanded on this statement: https://github.com/whatwg/html/issues/2791#issuecomment-892790934 and we were wondering if you'd be able to write a first draft? This would go into the "HTML Principles" Section of the doc: https://w3ctag.github.io/design-principles/#html

**Comment by jakearchibald** [comment]
I'll cook something up

**Comment by jakearchibald** [comment]
## External resources must not require pausing the HTML parser

As a page parses, the browser discovers assets that the page needs, and figures out a priority in which they should be loaded in parallel. This is disrupted by a resource which blocks the discovery of subsequent resources. At worst, it means the browser downloads items in series rather than parallel. At best, it means the browser queues downloads based on speculative parsing, which may turn out to be incorrect.

Features that block the parser generally do so because they want to feed additional content into the parser before subsequent content. This is the case of legacy `<script src="…">` elements, which can inject into the parser using `document.write(…)`. Due to the performance issues above, new features may not do this.

## Caution should be taken when blocking rendering on an external resource

If the browser needs to download an additional resource before rendering the page, it extends the time the user is looking at a blank page (or the previous page).

Features should only do this in order to prevent a worse user experience. For instance, blocking rendering on a stylesheet download makes sense, as the alternative is a flash of unstyled content.

**Comment by torgo** [comment]
Thank you @jakearchibald! 🙏🏻 We're gonna do a PR on this and iterate on it a bit.

**Comment by jakearchibald** [comment]
Sorry I dropped the ball on this. Combination of holiday then illness hasn't left me very productive 😞
