### ISSUE TITLE
Don't list me as editor

### ISSUE THREAD

**Issue by domenic** [w3ctag/design-principles#63]
I'm happy to see that especially over the last few TAG meetings this has become a very collaborative document with contributions from many TAG members. Although at some point I thought it might be good to have me in a supervisory role, reviewing PRs before they get merged, I think the current working mode where everyone on the TAG can be responsible for reviewing together is going great.

As such I think this is a good opportunity to mark the document has having "No editor". Then maybe we can change "Other Editorial Contributions" to "By" or something.

**Comment by slightlyoff** [comment]
Hey Domenic,

I'd like to avoid removing you entirely from the document as you did the majority of the work. Maybe we can add a list of contributors instead of removing all names?

Regards

**Comment by domenic** [comment]
We could work on adding an acknowledgment section, I suppose. But at this point I've written 7/20 sections so I'm not sure it's fair to say I did the majority :).

**Comment by torgo** [comment]
We have merged your PR. Unless you object we're going to list you as "former editor" on the document.

**Comment by domenic** [comment]
Hmm OK. My real intention here was that there would be no listed editor(s) prominently getting "credit", given what a collaborative enterprise this was. I guess that's not in the cards?

**Comment by plinss** [comment]
In my mind the editor is more of the current "caretaker" of the document, rather than the author, so listing one (or more) gives a point of contact and has utility. Former editors gives credit to those who did that job in the past (and provides a record). We intend to add an acknowledgements/contributors section to give credit to the contributors (and you'll be listed there as well, unless you no longer want to be associated with it, which we wanted to confirm).
