### ISSUE TITLE
provide advice on designing subclassable apis

### ISSUE THREAD

**Issue by dbaron** [w3ctag/design-principles#77]
@dominic was originally looking at making a separate document, but this probably could go into a section of the design principles document; at the very least that would make it easier to find (the TAG had forgotten about the old repository).

This section should cover the material in https://github.com/w3ctag/subclassable-apis-guide/issues , i.e.,:

w3ctag/subclassable-apis-guide#1
w3ctag/subclassable-apis-guide#2
w3ctag/subclassable-apis-guide#3
w3ctag/subclassable-apis-guide#4
w3ctag/subclassable-apis-guide#5

**Comment by dominic** [comment]
^ @domenic

**Comment by domenic** [comment]
My thinking has kind of evolved since that original work. I'm no longer convinced subclassable APIs of the type ECMAScript strives for are a great idea, or at least, if they are, they are not worth the trouble and mismatch with how things are generally implemented.

For example, in the "kernel method" design of https://github.com/w3ctag/subclassable-apis-guide/issues/1, to optimize things you generally need to detect if the kernel method has changed, and if not, take a fast path. This is annoying to implement.

What remains is subclassable APIs that are much less aggressive about their subclassability than ECMAScript APIs are. They wouldn't use the kernel method pattern, and brand checks retained everywhere.

To achieve this less-aggressive form, you just need a usable constructor. And that's basically #51. Once you have that, subclassing "just works".

So, let me take some time to address this and #51 together.
