### ISSUE TITLE
Synchronous events

### ISSUE THREAD

**Issue by annevk** [w3ctag/design-principles#81]
I never quite understand what this term means when I come across it. I guess it means dispatch it from something that occurs at least one task or microtask later?

But I'm also not sure the advice to always avoid them is good. E.g., we dispatch within the the abort algorithm directly to `AbortSignal`.

Another thing we should add is that you should change state in the same algorithm that the event is dispatched. That way you cannot observe state changes without the notification.

**Comment by travisleithead** [comment]
We have this current guidance in the doc: https://w3ctag.github.io/design-principles/#favor-asynchronous-events.

We can probably improve that guidance... :)

Re the definition, I think "synchronous events" are dispatched from an algorithm happening in a task--they are dispatched "in line" and are expected to complete before further steps of the algorithm are executed. (e.g., like the [focus update steps](https://html.spec.whatwg.org/multipage/interaction.html#focus-update-steps) that can run as part of the `focus()` API).

Indeed, as you note, the [`abort()`](https://dom.spec.whatwg.org/#dom-abortcontroller-abort) method of the `AbortController` starts an algorithm that synchronously fires `abort`. At this point, any author code may run, including code that could then call `abort()` again, causing a reentrancy into the platform and potential stack overflow--of course, you've carefully protected against this by adding an aborted flag which is allows the algorithm to gracefully unwind. Not everyone writing algorithms are as careful. By queuing the event instead of firing it directly, you avoid the reentrant scenario at the expense of one turn of the event loop.

**Comment by annevk** [comment]
You'd also introduce an observable delay in the cancelation and create a host of other issues you'd have to protect against. What if you invoke `abort()` twice in your setup?

Also, I know there's guidance in the document; this is feedback on that guidance not being great.

**Comment by travisleithead** [comment]
@annevk I hope to have improved this advice with #151. OK to close?

**Comment by annevk** [comment]
Yeah, thanks for tackling that and getting rid of a/synchronous!
